/**
 * IPC error code registry.
 *
 * Single source of truth for every error code that may flow back to the
 * renderer via `IpcResponse`. Use the `ipcError` helper in
 * `electron/main/ipc/_kit/errors.ts` to construct errors from these codes.
 */
export const IpcErrorCodes = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  STREAM_INIT_FAILED: "STREAM_INIT_FAILED",

  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_REQUIRED: "PROJECT_REQUIRED",

  CHAT_SESSION_NOT_FOUND: "CHAT_SESSION_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",

  PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
  APPLY_RUN_NOT_FOUND: "APPLY_RUN_NOT_FOUND",
  APPLY_RUN_NOT_READY: "APPLY_RUN_NOT_READY",
  APPLY_SESSION_NOT_READY: "APPLY_SESSION_NOT_READY",
  APPLY_RUN_PERSIST_FAILED: "APPLY_RUN_PERSIST_FAILED",
  STAGE_NOT_FOUND: "STAGE_NOT_FOUND",
  STAGE_TYPE_NOT_IMPLEMENTED: "STAGE_TYPE_NOT_IMPLEMENTED",

  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  INVALID_WORKFLOW_NAME: "INVALID_WORKFLOW_NAME",
  BUILT_IN_WORKFLOW: "BUILT_IN_WORKFLOW",

  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  ACP_ERROR: "ACP_ERROR",
  ACP_NOT_READY: "ACP_NOT_READY",
  ACP_EXIT_GIVEUP: "ACP_EXIT_GIVEUP",
  SPAWN_ERROR: "SPAWN_ERROR",

  YUNXIAO_API_ERROR: "YUNXIAO_API_ERROR",
} as const;

export type IpcErrorCode = (typeof IpcErrorCodes)[keyof typeof IpcErrorCodes];
